/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    fontFamily: {
      sans: [
        "<FONT_NAME>",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
        "sans-serif",
      ],
      serif: [
        "<FONT_NAME>",
        "ui-serif",
        "Georgia",
        "Cambria",
        "Times New Roman",
        "Times",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Apple Color Emoji",
        "Noto Color Emoji",
        "sans-serif",
      ],
      mono: [
        "<FONT_NAME>",
        "ui-monospace",
        "SFMono-Regular",
        "Menlo",
        "Monaco",
        "Consolas",
        "Liberation Mono",
        "Courier New",
        "monospace",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Apple Color Emoji",
        "Noto Color Emoji",
      ],
    },
    colors: {
      transparent: "transparent",
      current: "currentColor",
      black: "#000",
      white: "#fff",
      // <COLORS>
    },
    lineHeight: {
      DEFAULT: "1.5",
      1: "1",
      1.5: "1.5",
      1.6: "1.6",
    },
    spacing: {
      0: "0",
      1: "1px",
      2: "2px",
      4: "4px",
      8: "8px",
      16: "16px",
      32: "32px",
      48: "48px",
      64: "64px",
      list: "2ch",
    },
    borderWidth: {
      DEFAULT: "1px",
      0: "0",
      2: "2px",
      4: "4px",
    },
    borderRadius: {
      0: "0",
      2: "2px",
      4: "4px",
      8: "8px",
      16: "16px",
      full: "9999px",
    },
    extend: {
      screens: {
        "2xs": "375px",
        xs: "500px",
      },
      flex: {
        2: "2 2 0%",
      },
      backgroundSize: {
        stretch: "100% 100%",
      },
    },
  },
  plugins: [],
};
